services:
  mc:
    image: itzg/minecraft-server:java8
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    restart: unless-stopped
    environment:
      #DEBUG: "TRUE"
      EULA: "TRUE"
      #TYPE: FORGE
      MOD_PLATFORM: AUTO_CURSEFORGE
      CF_MODPACK_ZIP: /downloads/parasites.zip
      CF_API_KEY: ${CF_KEY} #declared in .env file
      CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/parasites-100-days/files/5115566
      #This mod messes everything up, might need to manually remove it from /mods-folder aswell
      CF_OVERRIDES_EXCLUSIONS: mods/voicechat-forge-1.12.2-2.4.32.jar
      CF_IGNORE_MISSING_FILES: mods/voicechat-forge-1.12.2-2.4.32.jar
      CF_EXCLUDE_MODS: mods/voicechat-forge-1.12.2-2.4.32.jar
      MOTD: "Lars... Lars never changes"
      MEMORY: 4G
      
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data
      - ./modpacks:/modpacks
      - ./downloads:/downloads